---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./helmreleases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kust-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomizes
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
