apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gabe565
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gabe565/charts/qbittorrent
  ref:
    tag: latest
