apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://jellyfin.github.io/jellyfin-helm
