apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cnpg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      version: 0.26.0
  install:
    createNamespace: true
  interval: 12h
  releaseName: cloudnative-pg
  targetNamespace: cnpg-system
  values:
    crds:
      enabled: true
