apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.10.0
  install:
    createNamespace: true
  interval: 12h
  releaseName: longhorn
  targetNamespace: longhorn-system
  values:
    service:
      ui:
        type: LoadBalancer
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultDataLocality: best-eefort
      migratable: true
      unmapMarkSnapChainRemoved: enabled
      dataEngine: v2
    preUpgradeChecker:
      jobEnabled: false
    defaultSettings:
      allowRecurringJobWhileVolumeDetached: true
      defaultDataPath: "/opt/longhorn"
      replicaAutoBalance: "true"
      storageOverProvisioningPercentage: "90"
      storageMinimalAvailablePercentage: "10"
      guaranteedInstanceManagerCPU: 1
      kubernetesClusterAutoscalerEnabled: "true"
      v2DataEngine: "true"
      dataEngineHugepageEnabled: true
      rwxVolumeFastFailover: "true"
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: cilium
      host: longhorn.svc.home
      tls: true
      secureBackends: true
      tlsSecret: tryzna-svc
      path: /
      pathType: ImplementationSpecific
