apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.13.0
  interval: 30m0s
  releaseName: metrics-server
  targetNamespace: kube-system
  values:
    args:
      - kubelet-insecure-tls
    metrics:
      enabled: true
    tls:
      type: "cert-manager"
      clusterDomain: cluster.local 
      certManager:
        addInjectorAnnotations: true
        existingIssuer:
          enabled: true
          kind: "ClusterIssuer"
          name: "tryzna-issuer"
        duration: "365d"
        renewBefore: "15d"

    

