apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-system
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 5m0s
  releaseName: metrics-server
  targetNamespace: metrics-server
